/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cms/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LessonCmsController_getSections"];
        put?: never;
        post: operations["LessonCmsController_createSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/sections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LessonCmsController_getSection"];
        put?: never;
        post?: never;
        delete: operations["LessonCmsController_deleteSection"];
        options?: never;
        head?: never;
        patch: operations["LessonCmsController_updateSection"];
        trace?: never;
    };
    "/cms/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LessonCmsController_getLesson"];
        put?: never;
        post?: never;
        delete: operations["LessonCmsController_deleteLesson"];
        options?: never;
        head?: never;
        patch: operations["LessonCmsController_updateLesson"];
        trace?: never;
    };
    "/cms/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LessonCmsController_createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LessonCmsController_createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["LessonCmsController_deletePage"];
        options?: never;
        head?: never;
        patch: operations["LessonCmsController_updatePage"];
        trace?: never;
    };
    "/cms/workers/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkerApiController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/workers/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkerApiController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkerApiController_createWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PageResponse: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Page text
             * @example Page one
             */
            text: string;
            /**
             * @description Page number
             * @example 1
             */
            pageNumber: number;
        };
        LessonResponse: {
            /** @example 48709c63-458e-4f90-8c39-577416a790f2 */
            id: string;
            /** @example Lesson one */
            text: string;
            pages: components["schemas"]["PageResponse"][];
        };
        SectionResponse: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Section text
             * @example Section one
             */
            text: string;
            lessons: components["schemas"]["LessonResponse"][];
        };
        SectionCreateRequest: {
            /**
             * @description Section text
             * @example Section one
             */
            text: string;
        };
        SectionUpdateRequest: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Section text
             * @example Section one
             */
            text: string;
        };
        LessonRequest: {
            /**
             * @description Lesson text
             * @example Lesson one
             */
            text: string;
        };
        LessonUpdateRequest: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Lesson text
             * @example Lesson one
             */
            text: string;
        };
        PageCreateRequest: {
            /**
             * @description Page text
             * @example Page one
             */
            text: string;
            /**
             * @description uuid
             * @example 4a2f7cce-548e-49d6-af56-c86f6f5a4e8d
             */
            lessonId: string;
            /**
             * @description Page number
             * @example 1
             */
            pageNumber: number;
        };
        PageUpdateRequest: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Page text
             * @example Page one
             */
            text?: string;
            /**
             * @description uuid
             * @example 4a2f7cce-548e-49d6-af56-c86f6f5a4e8d
             */
            lessonId?: string;
            /**
             * @description Page number
             * @example 1
             */
            pageNumber?: number;
        };
        SignInRequest: {
            /**
             * @description Worker email
             * @example admin@example.com
             */
            email: string;
            /**
             * @description Worker password
             * @example secret123
             */
            password: string;
        };
        WorkerAuthResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example 15m */
            expiresIn: string;
        };
        CreateWorkerRequest: {
            /**
             * @description Worker email
             * @example editor@example.com
             */
            email: string;
            /**
             * @description Worker password (min 6 chars)
             * @example secret123
             */
            password: string;
            /**
             * @description Worker role
             * @example editor
             * @enum {string}
             */
            role: "admin" | "editor";
            /**
             * @description Display name
             * @example John Doe
             */
            displayName?: string;
        };
        WorkerResponse: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id: string;
            /** @example editor@example.com */
            email: string;
            /**
             * @example editor
             * @enum {string}
             */
            role: "admin" | "editor";
            /** @example John Doe */
            displayName?: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    LessonCmsController_getSections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"][];
                };
            };
        };
    };
    LessonCmsController_createSection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    LessonCmsController_getSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    LessonCmsController_deleteSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonCmsController_updateSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonCmsController_getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    LessonCmsController_deleteLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonCmsController_updateLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonCmsController_createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    LessonCmsController_createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    LessonCmsController_deletePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonCmsController_updatePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    WorkerApiController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Returns access token in body, sets refresh token in httpOnly cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerAuthResponse"];
                };
            };
        };
    };
    WorkerApiController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issues a new access token using the httpOnly refresh token cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerAuthResponse"];
                };
            };
        };
    };
    WorkerApiController_createWorker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerRequest"];
            };
        };
        responses: {
            /** @description Create a new worker (admin only) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponse"];
                };
            };
        };
    };
}
