/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/lesson/get/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LessonApiController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lesson/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["LessonApiController_deleteOne"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lesson/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LessonApiController_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lesson/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LessonApiController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PageApiController_deletePage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PageApiController_updatePage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PageApiController_createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/section/find-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SectionApiController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/section/find/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SectionApiController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/section/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SectionApiController_deleteOne"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/section/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SectionApiController_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/section/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SectionApiController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/firebase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserApiController_signInWithFirebase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkerApiController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkerApiController_createWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LessonUpdateRequest: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Lesson text
             * @example Lesson one
             */
            text: string;
        };
        LessonRequest: {
            /**
             * @description Lesson text
             * @example Lesson one
             */
            text: string;
        };
        PageResponse: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Page text
             * @example Page one
             */
            text: string;
            /**
             * @description Page number
             * @example 1
             */
            pageNumber: number;
        };
        LessonResponse: {
            /** @example 48709c63-458e-4f90-8c39-577416a790f2 */
            id: string;
            /** @example Lesson one */
            text: string;
            pages: components["schemas"]["PageResponse"][];
        };
        PageUpdateRequest: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Page text
             * @example Page one
             */
            text?: string;
            /**
             * @description uuid
             * @example 4a2f7cce-548e-49d6-af56-c86f6f5a4e8d
             */
            lessonId?: string;
            /**
             * @description Page number
             * @example 1
             */
            pageNumber?: number;
        };
        PageCreateRequest: {
            /**
             * @description Page text
             * @example Page one
             */
            text: string;
            /**
             * @description uuid
             * @example 4a2f7cce-548e-49d6-af56-c86f6f5a4e8d
             */
            lessonId: string;
            /**
             * @description Page number
             * @example 1
             */
            pageNumber: number;
        };
        SectionResponse: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Section text
             * @example Section one
             */
            text: string;
            lessons: components["schemas"]["LessonResponse"][];
        };
        SectionUpdateRequest: {
            /**
             * @description uuid
             * @example 48709c63-458e-4f90-8c39-577416a790f2
             */
            id: string;
            /**
             * @description Section text
             * @example Section one
             */
            text: string;
        };
        SectionCreateRequest: {
            /**
             * @description Section text
             * @example Section one
             */
            text: string;
        };
        FirebaseAuthRequest: {
            /**
             * @description Firebase ID token
             * @example eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            idToken: string;
        };
        AuthResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example a3f8d2e1b0c4... */
            refreshToken: string;
            /** @example 15m */
            expiresIn: string;
        };
        SignInRequest: {
            /**
             * @description Worker email
             * @example admin@example.com
             */
            email: string;
            /**
             * @description Worker password
             * @example secret123
             */
            password: string;
        };
        WorkerAuthResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example a3f8d2e1b0c4... */
            refreshToken: string;
            /** @example 15m */
            expiresIn: string;
        };
        CreateWorkerRequest: {
            /**
             * @description Worker email
             * @example editor@example.com
             */
            email: string;
            /**
             * @description Worker password (min 6 chars)
             * @example secret123
             */
            password: string;
            /**
             * @description Worker role
             * @example editor
             * @enum {string}
             */
            role: "admin" | "editor";
            /**
             * @description Display name
             * @example John Doe
             */
            displayName?: string;
        };
        WorkerResponse: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id: string;
            /** @example editor@example.com */
            email: string;
            /**
             * @example editor
             * @enum {string}
             */
            role: "admin" | "editor";
            /** @example John Doe */
            displayName?: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    LessonApiController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"] | null;
                };
            };
        };
    };
    LessonApiController_deleteOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonApiController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdateRequest"];
            };
        };
        responses: {
            /** @description Update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    LessonApiController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            /** @description Create */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    PageApiController_deletePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description uuid */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete one page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    PageApiController_updatePage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageUpdateRequest"];
            };
        };
        responses: {
            /** @description Update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    PageApiController_createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageCreateRequest"];
            };
        };
        responses: {
            /** @description Create */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    SectionApiController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"][];
                };
            };
        };
    };
    SectionApiController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    SectionApiController_deleteOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    SectionApiController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionUpdateRequest"];
            };
        };
        responses: {
            /** @description Update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    SectionApiController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreateRequest"];
            };
        };
        responses: {
            /** @description Create */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    UserApiController_signInWithFirebase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FirebaseAuthRequest"];
            };
        };
        responses: {
            /** @description Sign in with Firebase token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    WorkerApiController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Sign in with email and password */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerAuthResponse"];
                };
            };
        };
    };
    WorkerApiController_createWorker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerRequest"];
            };
        };
        responses: {
            /** @description Create a new worker */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponse"];
                };
            };
        };
    };
}
